"""Data models for the modernized RAG pipeline."""

from typing import List, Literal, Optional, Dict, TypedDict
from pydantic import BaseModel, Field
from enum import Enum


class SearchMode(str, Enum):
    """Search modes supported by the pipeline."""
    HYBRID = "hybrid"
    VECTOR = "vector"
    SEMANTIC = "semantic"


class SearchConfigV2(TypedDict):
    """Configuration for search parameters - V2 with enhanced options."""

    chunk_count: int
    use_semantic_ranker: bool
    use_query_rewrite: bool
    use_knowledge_base: bool
    use_streaming: bool
    query_rewrite_count: int
    scoring_profile: Optional[str]
    search_mode: str


class KnowledgeBaseConfig(TypedDict):
    """Configuration for Azure AI Search Knowledge Base."""

    name: str
    knowledge_sources: List[str]
    model_deployment: str
    model_name: str


class SubQuery(BaseModel):
    """A decomposed subquery from the query planner."""

    query: str = Field(description="The subquery text")
    intent: str = Field(description="What this subquery aims to find")
    filters: Optional[Dict[str, str]] = Field(default=None, description="Optional filters to apply")


class QueryPlan(BaseModel):
    """Query plan generated by the query planner."""

    original_query: str = Field(description="The original user query")
    subqueries: List[SubQuery] = Field(description="Decomposed subqueries")
    reasoning: str = Field(description="Explanation of the query decomposition")


class RetrievalResult(TypedDict):
    """Structure for individual retrieval results."""

    ref_id: str
    content: dict
    content_type: Literal["text", "image"]
    score: float
    reranker_score: Optional[float]
    source_subquery: Optional[str]


class RetrievalResults(TypedDict):
    """Structure for retrieval results with metadata."""

    references: List[RetrievalResult]
    subqueries: List[str]
    query_rewrites: List[str]
    total_results: int


class AnswerFormat(BaseModel):
    """Format for chat completion responses with citations."""

    answer: str = Field(description="The answer in Markdown format")
    text_citations: List[str] = Field(default=[], description="Text reference IDs used")
    image_citations: List[str] = Field(default=[], description="Image reference IDs used")


class Citation(TypedDict):
    """Structure for a citation reference."""

    ref_id: str
    content_type: Literal["text", "image"]
    location_metadata: Optional[dict]
    text: Optional[str]
    title: Optional[str]
    doc_id: str


class MessageContent(TypedDict):
    """Content of a message."""

    text: str
    type: Literal["text"]


class Message(TypedDict):
    """A chat message."""

    role: Literal["user", "assistant", "system"]
    content: List[MessageContent]


class PipelineStep(TypedDict):
    """A step in the RAG pipeline for observability."""

    name: str
    status: Literal["pending", "running", "completed", "failed"]
    duration_ms: Optional[int]
    metadata: Optional[dict]
